import type { EnglishSkill, Question, Tier } from "./types";

type Spec = {
  id: string;
  difficulty: Tier;
  skill: EnglishSkill;
  stem: string;
  options: [string, string, string, string];
  correctIndex: 0 | 1 | 2 | 3;
  explanation: string;
  passage?: string;
  passageId?: string;
};

function eq(s: Spec): Question {
  return { subject: "english", ...s };
}

const P1 = `Cities are often described as engines of growth, yet the quietest parts of a city may do as much work as the loudest. Parks do not produce goods, and they do not appear in most ledgers of productivity. They do, however, lower the temperature of streets, give children a place that is not a shop, and offer adults a pause that costs nothing. When a council sells a green square for apartments, the gain is easy to count: new homes, new taxes. The loss is slower and harder to name. A city that keeps only what can be priced will slowly discover that some of the things it sold were the reasons people wanted to live there at all.`;

const P2 = `A scientific model is not a tiny copy of the world. It is a set of deliberate simplifications, kept because they help us predict what will happen next. The frictionless plane in a physics textbook is not a lie; it is a tool. Trouble begins when a model is treated as a portrait rather than a sketch. Weather forecasts fail not because scientists are careless, but because the atmosphere is more entangled than any practical model can be. The honest scientist therefore speaks in ranges and likelihoods. Certainty, in this craft, is usually a sign that the speaker has forgotten what a model is for.`;

const P3 = `Oral history is sometimes dismissed as unreliable because memory is fallible. Written records, by contrast, look solid: dates, signatures, official stamps. Yet a document can freeze a single official version of events, while a community's stories may preserve what the stamp never bothered to notice. The farmer's account of a flood, repeated across a generation, can locate a river's old path more accurately than a colonial map drawn from a distant hill. The task is not to crown one form of evidence and discard the other. It is to ask, of every source, who made it, for whom, and what they had reason to leave out.`;

const P4 = `Attention is not a fountain. It is a budget, and most of us overspend it before noon. A paragraph of serious prose asks the reader to hold several claims at once, to notice a qualifier, to resist the first conclusion. Skimming is not a moral failure; it is a rational response to a world that throws more text at us than any mind can keep. The cost appears later. When a test, a contract, or a ballot depends on a single word — not, except, only — the skimming habit, so useful on a phone, becomes expensive. Reading slowly, on purpose, is less a talent than a refusal to be hurried past the point.`;

const P5 = `Incentives do not merely reward work; they reshape what people think work is. Pay a school only for exam scores, and the school will teach the exam. Pay a hospital only for the number of patients seen, and waiting rooms will empty faster than illnesses. This is not because teachers or doctors are cynical. It is because organisations, like people, follow the scoreboard they are given. A well-designed measure is therefore not a technical afterthought. It is a statement of what we actually value. If the scoreboard is crude, even honourable people will be pulled toward crude behaviour.`;

const P6 = `Birds that vanish from a garden in September are not lost. They are running an old calendar. Migration is a bet placed on seasons: that insects will thicken somewhere north, that winter will thin the food at home, that a body small enough to lift can still cross a sea. The routes look like freedom from the ground. From the bird's point of view they are closer to a timetable, inherited and then adjusted by weather. When climate shifts the timetable, the inherited map lags. A species does not fail because it is unintelligent. It fails because the world changed faster than the map.`;

const P7 = `A constitution is often imagined as a rulebook for citizens. It is better understood as a rulebook for power. It says who may tax, who may punish, who may send an army, and — just as important — who may not. The dull clauses about procedure are not decorations. They are the point. A government that can skip its own steps whenever the steps are inconvenient is not using a constitution; it is wearing one. The test of such a document is not how moving its preamble sounds. It is whether, on an ordinary Tuesday, an official with every reason to rush still has to wait for a signature that is not his own.`;

const P8 = `Soil is easy to treat as dirt: the stuff that gets in the way of the seed. Farmers know otherwise. A handful of living soil is a city of bacteria, fungi, and small animals, trading nutrients in the dark. Strip the cover from a field, and rain will carry that city into a river. Add only chemical feed for a decade, and the crop may still stand while the underground city thins. Yield measured this year can hide a debt that comes due in twenty. Agriculture, at its most serious, is less a victory over nature than a long negotiation with a living floor.`;

const P9 = `Libraries look old-fashioned next to a search bar. Type a question, and an answer arrives in a second, ranked by popularity or paid placement. A library does something slower and ruder: it lets a reader wander into a shelf she did not know she needed. Discovery of that kind cannot be fully predicted, which is why it is hard to defend in a budget meeting. Yet many of the better arguments in public life began as accidents in a stack. Efficiency is a virtue in a warehouse. In a culture, a little inefficiency — time to take the wrong book off the shelf — is closer to oxygen.`;

const P10 = `Numbers in a newspaper are often asked to do a job they cannot do: settle an argument by themselves. “Crime is up 20%” sounds like a conclusion. It is only a comparison, and a comparison without a base is a rumour in digits. Up 20% from what, over how long, counted how? A town with two robberies last year and three this year has a 50% increase and almost no crime. The honest reader therefore hunts for the denominator. Without it, a statistic is not information. It is a costume that information sometimes wears.`;

export const ENGLISH_BANK: Question[] = [
  eq({
    id: "en|p1|1",
    difficulty: "easy",
    skill: "reading-comprehension",
    passageId: "p1",
    passage: P1,
    stem: "The author's primary purpose is to",
    options: [
      "argue that parks create value a city cannot fully price",
      "list the recreational facilities a modern city should build",
      "criticise apartment construction as always harmful",
      "explain how councils calculate property tax",
    ],
    correctIndex: 0,
    explanation:
      "The passage contrasts easy-to-count gains with slower, unnamed losses, and ends on reasons people want to live in a city. Listing facilities or attacking all apartments overstates; tax method is never discussed.",
  }),
  eq({
    id: "en|p1|2",
    difficulty: "easy",
    skill: "reading-comprehension",
    passageId: "p1",
    passage: P1,
    stem: "In the passage, the phrase “the gain is easy to count” refers to",
    options: [
      "new homes and taxes from selling a green square",
      "the drop in street temperature that parks produce",
      "the number of children who use a park each week",
      "the price of apartments in a growing city",
    ],
    correctIndex: 0,
    explanation:
      "The sentence names the gain: new homes, new taxes. The other options are either losses/benefits of parks or unstated figures.",
  }),
  eq({
    id: "en|p1|3",
    difficulty: "hard",
    skill: "reading-comprehension",
    passageId: "p1",
    passage: P1,
    stem: "Which statement best captures the author's attitude toward selling parks?",
    options: [
      "Wary — the visible profit hides a harder-to-name cost",
      "Neutral — the author only reports what councils do",
      "Enthusiastic — apartments are presented as the city's real work",
      "Dismissive — parks are called unproductive and therefore expendable",
    ],
    correctIndex: 0,
    explanation:
      "Tone is cautionary, not celebratory. “Quietest parts may do as much work” undercuts the idea that parks are expendable. Neutrality is a trap: the close is a judgement.",
  }),
  eq({
    id: "en|p2|1",
    difficulty: "easy",
    skill: "reading-comprehension",
    passageId: "p2",
    passage: P2,
    stem: "According to the passage, a scientific model is best described as",
    options: [
      "a set of simplifications kept because they predict",
      "a miniature, accurate copy of the real world",
      "a portrait that should match every detail of nature",
      "a forecast that is useless if it is ever wrong",
    ],
    correctIndex: 0,
    explanation:
      "Sentence two defines a model as deliberate simplifications kept for prediction. “Tiny copy” and “portrait” are the views the author rejects.",
  }),
  eq({
    id: "en|p2|2",
    difficulty: "hard",
    skill: "reading-comprehension",
    passageId: "p2",
    passage: P2,
    stem: "The frictionless plane is mentioned in order to",
    options: [
      "show that a useful model may omit real features on purpose",
      "prove that physics textbooks are outdated",
      "argue that friction should never be ignored",
      "give an example of a forecast that failed",
    ],
    correctIndex: 0,
    explanation:
      "The plane “is not a lie; it is a tool.” The author is illustrating simplification, not attacking textbooks or weather.",
  }),
  eq({
    id: "en|p2|3",
    difficulty: "difficult",
    skill: "vocabulary-in-context",
    passageId: "p2",
    passage: P2,
    stem: "In the last sentence, “craft” most nearly means",
    options: [
      "discipline or practice",
      "handmade physical object",
      "clever trick used to deceive",
      "school subject called design",
    ],
    correctIndex: 0,
    explanation:
      "Here craft = the work of science. The everyday sense “handmade object” is the common-meaning trap.",
  }),
  eq({
    id: "en|p3|1",
    difficulty: "hard",
    skill: "reading-comprehension",
    passageId: "p3",
    passage: P3,
    stem: "The author suggests that written records can be limited because they",
    options: [
      "may freeze a single official version of events",
      "are always forged by colonial officers",
      "cannot include dates or signatures",
      "are less fallible than memory and therefore complete",
    ],
    correctIndex: 0,
    explanation:
      "The passage says a document can freeze one official version. It does not say all records are forged, and it grants that they look solid.",
  }),
  eq({
    id: "en|p3|2",
    difficulty: "hard",
    skill: "reading-comprehension",
    passageId: "p3",
    passage: P3,
    stem: "The farmer's flood story is used as evidence that",
    options: [
      "oral accounts can preserve details a map missed",
      "farmers remember every flood more accurately than scientists",
      "colonial maps should be thrown away",
      "memory is never fallible in rural communities",
    ],
    correctIndex: 0,
    explanation:
      "The example is modest: oral history can locate an old river path better than one distant map. Absolute claims about farmers or maps go beyond the text.",
  }),
  eq({
    id: "en|p3|3",
    difficulty: "difficult",
    skill: "reading-comprehension",
    passageId: "p3",
    passage: P3,
    stem: "Which of the following would the author most likely recommend?",
    options: [
      "Weigh each source by asking who made it and what it omitted",
      "Trust only documents with official stamps",
      "Replace archives with interviews in every historical study",
      "Treat all oral history as more accurate than maps",
    ],
    correctIndex: 0,
    explanation:
      "The last two sentences reject crowning one form of evidence. The method is interrogation of every source.",
  }),
  eq({
    id: "en|p4|1",
    difficulty: "easy",
    skill: "reading-comprehension",
    passageId: "p4",
    passage: P4,
    stem: "The author compares attention to a budget primarily to emphasise that it is",
    options: [
      "limited and easily overspent",
      "something only governments control",
      "increased by using a phone",
      "unrelated to reading speed",
    ],
    correctIndex: 0,
    explanation:
      "“Most of us overspend it before noon” makes the scarcity point. Government and phones are neighbouring ideas, not the comparison's purpose.",
  }),
  eq({
    id: "en|p4|2",
    difficulty: "hard",
    skill: "reading-comprehension",
    passageId: "p4",
    passage: P4,
    stem: "The author regards skimming as",
    options: [
      "understandable in daily life, costly when a single word matters",
      "a moral failure that serious students must eliminate",
      "the best way to read contracts and ballots",
      "proof that modern readers cannot handle paragraphs",
    ],
    correctIndex: 0,
    explanation:
      "Skimming is “not a moral failure” but later “expensive” on tests and contracts. The trap is the moral-failure reading the author explicitly rejects.",
  }),
  eq({
    id: "en|p4|3",
    difficulty: "difficult",
    skill: "vocabulary-in-context",
    passageId: "p4",
    passage: P4,
    stem: "The word “qualifier” in the passage is closest in meaning to",
    options: [
      "a word that limits or conditions a claim",
      "a person who has passed an exam",
      "a certificate of professional skill",
      "a high score on a practice test",
    ],
    correctIndex: 0,
    explanation:
      "In reading, a qualifier is a limiting word (not, except, only). “Person who passed an exam” is the common-meaning trap.",
  }),
  eq({
    id: "en|p5|1",
    difficulty: "hard",
    skill: "reading-comprehension",
    passageId: "p5",
    passage: P5,
    stem: "The examples of the school and the hospital are meant to show that",
    options: [
      "crude scoreboards pull even honourable people toward crude behaviour",
      "teachers and doctors are generally cynical about their work",
      "exams and waiting times should be abolished",
      "organisations cannot be measured at all",
    ],
    correctIndex: 0,
    explanation:
      "The author denies cynicism and concludes that a crude scoreboard reshapes behaviour. Abolition and “cannot be measured” overreach.",
  }),
  eq({
    id: "en|p5|2",
    difficulty: "difficult",
    skill: "reading-comprehension",
    passageId: "p5",
    passage: P5,
    stem: "Which assumption does the argument rely on?",
    options: [
      "People and organisations respond to the measures they are judged by",
      "All hospitals already empty their waiting rooms too quickly",
      "Exam scores have no connection to real learning",
      "Incentives never work in public institutions",
    ],
    correctIndex: 0,
    explanation:
      "The whole chain — pay for X, get X — assumes agents follow the scoreboard. The other options are stronger than anything claimed.",
  }),
  eq({
    id: "en|p6|1",
    difficulty: "easy",
    skill: "reading-comprehension",
    passageId: "p6",
    passage: P6,
    stem: "The author's main point about migration is that it is",
    options: [
      "an inherited timetable that can lag when climate shifts",
      "proof that birds are free in a way humans are not",
      "a random wandering with no pattern",
      "a recent behaviour caused only by cities",
    ],
    correctIndex: 0,
    explanation:
      "Routes “are closer to a timetable,” and climate can make the map lag. Freedom from the ground is what the author undercuts.",
  }),
  eq({
    id: "en|p6|2",
    difficulty: "hard",
    skill: "reading-comprehension",
    passageId: "p6",
    passage: P6,
    stem: "When the author says a species “fails because the world changed faster than the map,” “the map” refers to",
    options: [
      "inherited migratory routes and timing",
      "a paper chart drawn by scientists",
      "the garden from which birds vanish",
      "the sea the birds must cross",
    ],
    correctIndex: 0,
    explanation:
      "The map is metaphorical: the inherited timetable. A paper chart is the literal trap.",
  }),
  eq({
    id: "en|p7|1",
    difficulty: "hard",
    skill: "reading-comprehension",
    passageId: "p7",
    passage: P7,
    stem: "The author believes the most important parts of a constitution are",
    options: [
      "the dull clauses that force even a hurried official to wait",
      "the moving language of the preamble",
      "the sections that list citizens' everyday duties",
      "the rules that let government skip steps in an emergency",
    ],
    correctIndex: 0,
    explanation:
      "“The dull clauses about procedure are not decorations. They are the point.” The preamble is explicitly downgraded.",
  }),
  eq({
    id: "en|p7|2",
    difficulty: "difficult",
    skill: "reading-comprehension",
    passageId: "p7",
    passage: P7,
    stem: "A government “wearing” a constitution, in this passage, is one that",
    options: [
      "keeps the document's appearance while skipping its constraints",
      "prints the constitution on official uniforms",
      "follows every procedure even when it is inconvenient",
      "has not yet written a preamble",
    ],
    correctIndex: 0,
    explanation:
      "Wearing vs using: skipping steps whenever inconvenient. Following procedure is the opposite of the metaphor.",
  }),
  eq({
    id: "en|p8|1",
    difficulty: "easy",
    skill: "reading-comprehension",
    passageId: "p8",
    passage: P8,
    stem: "The author compares living soil to a city in order to",
    options: [
      "stress that soil is a busy community, not empty dirt",
      "argue that farms should be moved into urban areas",
      "show that bacteria pay taxes in nutrient markets",
      "claim that soil and cities have the same population",
    ],
    correctIndex: 0,
    explanation:
      "The metaphor makes underground life vivid. Taking it literally (taxes, population) is the trap.",
  }),
  eq({
    id: "en|p8|2",
    difficulty: "hard",
    skill: "reading-comprehension",
    passageId: "p8",
    passage: P8,
    stem: "“A debt that comes due in twenty” most nearly refers to",
    options: [
      "long-term damage hidden by this year's yield",
      "a bank loan used to buy fertiliser",
      "the twenty-year life of a tractor",
      "taxes farmers will owe in two decades",
    ],
    correctIndex: 0,
    explanation:
      "Yield this year can hide thinning underground life. Bank-loan is the common-meaning trap for “debt.”",
  }),
  eq({
    id: "en|p9|1",
    difficulty: "hard",
    skill: "reading-comprehension",
    passageId: "p9",
    passage: P9,
    stem: "The author values libraries chiefly because they",
    options: [
      "allow unplanned discovery that a search bar does not",
      "rank answers by popularity faster than the internet",
      "are cheaper to run than a warehouse",
      "replace the need for public argument",
    ],
    correctIndex: 0,
    explanation:
      "Wandering into an unexpected shelf is the contrast with the search bar. Popularity ranking is what the search bar does.",
  }),
  eq({
    id: "en|p9|2",
    difficulty: "difficult",
    skill: "vocabulary-in-context",
    passageId: "p9",
    passage: P9,
    stem: "In the passage, “ruder” most nearly means",
    options: [
      "less obedient to the user's first question",
      "less polite to librarians",
      "more poorly designed as a building",
      "more expensive for a city budget",
    ],
    correctIndex: 0,
    explanation:
      "Ruder = less compliant: it makes you wander. Politeness is the common-meaning trap.",
  }),
  eq({
    id: "en|p10|1",
    difficulty: "easy",
    skill: "reading-comprehension",
    passageId: "p10",
    passage: P10,
    stem: "The author's advice to the reader is to",
    options: [
      "look for the base or denominator behind a striking percentage",
      "ignore all crime statistics in newspapers",
      "assume that a 20% rise always means danger",
      "prefer rumours to official counts",
    ],
    correctIndex: 0,
    explanation:
      "“The honest reader therefore hunts for the denominator.” Ignoring all statistics overshoots.",
  }),
  eq({
    id: "en|p10|2",
    difficulty: "hard",
    skill: "reading-comprehension",
    passageId: "p10",
    passage: P10,
    stem: "The town with two robberies, then three, is mentioned to show that",
    options: [
      "a large percentage change can describe a tiny real change",
      "crime is falling in most small towns",
      "three robberies are always worse than a 20% rise elsewhere",
      "newspapers should stop using numbers",
    ],
    correctIndex: 0,
    explanation:
      "50% from a base of two is the illustration. The passage does not generalise about actual crime trends.",
  }),

  // Vocabulary in context
  eq({
    id: "en|vic|1",
    difficulty: "easy",
    skill: "vocabulary-in-context",
    stem: "Although the mayor's speech was brief, it was so lucid that even children followed the argument. As used here, lucid means",
    options: ["clear", "loud", "long", "fancy"],
    correctIndex: 0,
    explanation: "Clue: even children followed the argument → clear. Loud/long/fancy are neighbouring qualities of speeches.",
  }),
  eq({
    id: "en|vic|2",
    difficulty: "easy",
    skill: "vocabulary-in-context",
    stem: "The drought left the reservoir sparse; boats sat on cracked mud. Sparse means",
    options: ["thinly supplied", "frozen", "poisoned", "deep"],
    correctIndex: 0,
    explanation: "Boats on cracked mud → little water. Frozen/poisoned/deep do not fit the image.",
  }),
  eq({
    id: "en|vic|3",
    difficulty: "easy",
    skill: "vocabulary-in-context",
    stem: "Her apology was candid: she named the mistake and did not dress it up. Candid means",
    options: ["frank", "secret", "angry", "rehearsed"],
    correctIndex: 0,
    explanation: "Named the mistake, no dressing up → frank. Rehearsed is nearly an opposite.",
  }),
  eq({
    id: "en|vic|4",
    difficulty: "hard",
    skill: "vocabulary-in-context",
    stem: "The committee's praise was tepid; nobody argued, and nobody sounded convinced. Tepid means",
    options: ["unenthusiastic", "illegal", "unanimous", "overheated"],
    correctIndex: 0,
    explanation: "Nobody sounded convinced → lukewarm. Unanimous confuses silence with agreement; overheated is the temperature antonym.",
  }),
  eq({
    id: "en|vic|5",
    difficulty: "hard",
    skill: "vocabulary-in-context",
    stem: "He tried to mitigate the damage by repairing the roof before the next storm. Mitigate means",
    options: ["make less severe", "measure carefully", "advertise", "ignore"],
    correctIndex: 0,
    explanation: "Repairing before the storm reduces harm. “Measure” is a look-alike trap (metric/mitigate).",
  }),
  eq({
    id: "en|vic|6",
    difficulty: "hard",
    skill: "vocabulary-in-context",
    stem: "The two reports were not contradictory so much as complementary: each filled a gap in the other. Complementary means",
    options: ["completing one another", "full of praise", "copied from each other", "impossible to compare"],
    correctIndex: 0,
    explanation: "Each filled a gap → they complete each other. Complimentary (praise) is the spelling/meaning trap.",
  }),
  eq({
    id: "en|vic|7",
    difficulty: "difficult",
    skill: "vocabulary-in-context",
    stem: "The novel's ending was equivocal; readers could defend two opposite morals with equal ease. Equivocal means",
    options: ["ambiguous", "equal in length", "loudly moral", "hastily written"],
    correctIndex: 0,
    explanation: "Two opposite morals → ambiguous. Equal-in-length hears “equi-” and stops.",
  }),
  eq({
    id: "en|vic|8",
    difficulty: "difficult",
    skill: "vocabulary-in-context",
    stem: "Nothing in the minutes corroborated the rumour that the vote had been delayed. Corroborated means",
    options: ["supported with evidence", "invented", "translated", "celebrated"],
    correctIndex: 0,
    explanation: "Minutes would support or fail to support a rumour. Invented is almost an opposite.",
  }),
  eq({
    id: "en|vic|9",
    difficulty: "difficult",
    skill: "vocabulary-in-context",
    stem: "The governor's modest motorcade was a tacit rebuke to the previous display of luxury. Tacit means",
    options: ["unspoken but implied", "temporary", "illegal", "publicly announced"],
    correctIndex: 0,
    explanation: "The rebuke is carried by the modest display, not by a speech. Announced is the opposite.",
  }),
  eq({
    id: "en|vic|10",
    difficulty: "easy",
    skill: "vocabulary-in-context",
    stem: "The instructions were so ambiguous that half the class started on page one and half on page four. Ambiguous means",
    options: ["open to more than one reading", "printed too small", "written in another language", "missing entirely"],
    correctIndex: 0,
    explanation: "Two different starts → more than one reading. Small print is a neighbouring complaint.",
  }),
  eq({
    id: "en|vic|11",
    difficulty: "hard",
    skill: "vocabulary-in-context",
    stem: "She gave a pragmatic reason for walking: the bus would not arrive for an hour. Pragmatic means",
    options: ["practical", "proud", "poetic", "political"],
    correctIndex: 0,
    explanation: "The bus delay is a practical reason. Political/poetic are look-alike openings (pra-/poe-).",
  }),
  eq({
    id: "en|vic|12",
    difficulty: "hard",
    skill: "vocabulary-in-context",
    stem: "His claim that the bridge was “perfectly safe” proved premature: it closed the next week. Premature means",
    options: ["too early to be justified", "carefully tested", "required by law", "spoken in public"],
    correctIndex: 0,
    explanation: "The later closure shows the claim came too soon. “Carefully tested” fights the sentence.",
  }),
  eq({
    id: "en|vic|13",
    difficulty: "difficult",
    skill: "vocabulary-in-context",
    stem: "The essay's first page was ornate; the second, by contrast, was austere. Austere means",
    options: ["plain and severe in style", "longer", "humorous", "full of decoration"],
    correctIndex: 0,
    explanation: "Contrast with ornate → plain. “Full of decoration” is the antonym trap.",
  }),
  eq({
    id: "en|vic|14",
    difficulty: "easy",
    skill: "vocabulary-in-context",
    stem: "To conserve water, the village opened the public tap only at dawn and dusk. Conserve means",
    options: ["use sparingly so a supply lasts", "boil", "flavour", "export"],
    correctIndex: 0,
    explanation: "Limited hours → sparing use. Boil is a neighbouring water-verb.",
  }),
  eq({
    id: "en|vic|15",
    difficulty: "difficult",
    skill: "vocabulary-in-context",
    stem: "The witness's account was plausible but not yet proven. Plausible means",
    options: ["seeming reasonable", "already verified", "spoken under oath", "intentionally false"],
    correctIndex: 0,
    explanation: "“But not yet proven” splits seeming-reasonable from verified. Verified is the trap.",
  }),
  eq({
    id: "en|vic|16",
    difficulty: "hard",
    skill: "vocabulary-in-context",
    stem: "The new rule will supersede the 2019 guideline from next term. Supersede means",
    options: ["take the place of", "copy", "translate into law for the first time", "weaken slightly"],
    correctIndex: 0,
    explanation: "A new rule replacing an old guideline. Copy/weaken miss the replacement sense.",
  }),
  eq({
    id: "en|vic|17",
    difficulty: "easy",
    skill: "vocabulary-in-context",
    stem: "The path was so steep that even a brief rest felt indispensable. Indispensable means",
    options: ["impossible to do without", "optional", "dangerous", "expensive"],
    correctIndex: 0,
    explanation: "On a steep path, rest is needed. Optional is the antonym.",
  }),
  eq({
    id: "en|vic|18",
    difficulty: "difficult",
    skill: "vocabulary-in-context",
    stem: "Her criticism was trenchant: one sentence named the flaw others had danced around. Trenchant means",
    options: ["sharp and effective", "long-winded", "kindly vague", "copied from a review"],
    correctIndex: 0,
    explanation: "One sentence naming the flaw → incisive. Long-winded fights “one sentence.”",
  }),

  // Subject-verb agreement
  eq({
    id: "en|sva|1",
    difficulty: "easy",
    skill: "subject-verb-agreement",
    stem: "Choose the correct sentence.",
    options: [
      "The list of required books is on the board.",
      "The list of required books are on the board.",
      "The list of required books were on the board.",
      "The list of required books have been on the board.",
    ],
    correctIndex: 0,
    explanation: "Subject is list (singular), not books. Ignore the prepositional phrase.",
  }),
  eq({
    id: "en|sva|2",
    difficulty: "easy",
    skill: "subject-verb-agreement",
    stem: "Neither of the answers ____ correct.",
    options: ["is", "are", "were", "have been"],
    correctIndex: 0,
    explanation: "Neither is singular. Are/were agree with the nearest noun (answers), which is the trap.",
  }),
  eq({
    id: "en|sva|3",
    difficulty: "hard",
    skill: "subject-verb-agreement",
    stem: "Each of the players ____ given a new jersey.",
    options: ["was", "were", "are", "have been"],
    correctIndex: 0,
    explanation: "Each is singular → was. Players is the distractor.",
  }),
  eq({
    id: "en|sva|4",
    difficulty: "hard",
    skill: "subject-verb-agreement",
    stem: "The news from the outposts ____ worse than expected.",
    options: ["is", "are", "were", "have"],
    correctIndex: 0,
    explanation: "News is singular in standard English, though it looks plural.",
  }),
  eq({
    id: "en|sva|5",
    difficulty: "hard",
    skill: "subject-verb-agreement",
    stem: "Mathematics ____ her strongest subject, not the sciences.",
    options: ["is", "are", "were", "have been"],
    correctIndex: 0,
    explanation: "Mathematics (the subject name) takes a singular verb. Sciences is a contrast, not the subject.",
  }),
  eq({
    id: "en|sva|6",
    difficulty: "difficult",
    skill: "subject-verb-agreement",
    stem: "The committee, together with the two advisers, ____ decided to delay the vote.",
    options: ["has", "have", "are", "were"],
    correctIndex: 0,
    explanation: "Together with does not make a compound subject. Committee remains singular → has.",
  }),
  eq({
    id: "en|sva|7",
    difficulty: "easy",
    skill: "subject-verb-agreement",
    stem: "There ____ several reasons to start with the easy questions.",
    options: ["are", "is", "was", "has"],
    correctIndex: 0,
    explanation: "Reasons (plural) is the true subject after there. Is agrees with the dummy there.",
  }),
  eq({
    id: "en|sva|8",
    difficulty: "difficult",
    skill: "subject-verb-agreement",
    stem: "One of the boxes that ____ missing has been found in the store.",
    options: ["were", "was", "is", "has"],
    correctIndex: 0,
    explanation: "That refers to boxes (plural), so were missing. The later has agrees with one, which is a different clause.",
  }),
  eq({
    id: "en|sva|9",
    difficulty: "hard",
    skill: "subject-verb-agreement",
    stem: "Bread and butter ____ his usual breakfast.",
    options: ["is", "are", "were", "have"],
    correctIndex: 0,
    explanation: "Treated as one dish → singular. Are treats the pair as two meals.",
  }),
  eq({
    id: "en|sva|10",
    difficulty: "easy",
    skill: "subject-verb-agreement",
    stem: "The quality of the essays ____ improved this term.",
    options: ["has", "have", "are", "were"],
    correctIndex: 0,
    explanation: "Quality is singular. Essays is the interrupting-phrase trap.",
  }),
  eq({
    id: "en|sva|11",
    difficulty: "difficult",
    skill: "subject-verb-agreement",
    stem: "Neither the principal nor the teachers ____ willing to cancel the match.",
    options: ["are", "is", "was", "has been"],
    correctIndex: 0,
    explanation: "With neither…nor, the verb agrees with the nearer subject: teachers → are.",
  }),
  eq({
    id: "en|sva|12",
    difficulty: "hard",
    skill: "subject-verb-agreement",
    stem: "A number of students ____ late because the bus broke down.",
    options: ["were", "was", "is", "has been"],
    correctIndex: 0,
    explanation: "A number of = several → plural. The number of would be singular — the neighbouring construction.",
  }),
  eq({
    id: "en|sva|13",
    difficulty: "difficult",
    skill: "subject-verb-agreement",
    stem: "The number of applications ____ fallen since last year.",
    options: ["has", "have", "are", "were"],
    correctIndex: 0,
    explanation: "The number is singular → has. A number of would take have.",
  }),
  eq({
    id: "en|sva|14",
    difficulty: "easy",
    skill: "subject-verb-agreement",
    stem: "My brother, as well as his friends, ____ arriving tonight.",
    options: ["is", "are", "were", "have been"],
    correctIndex: 0,
    explanation: "As well as does not change the true subject: brother.",
  }),
  eq({
    id: "en|sva|15",
    difficulty: "hard",
    skill: "subject-verb-agreement",
    stem: "Five kilometres ____ a long way to walk in this heat.",
    options: ["is", "are", "were", "have been"],
    correctIndex: 0,
    explanation: "A measurement taken as one distance is singular.",
  }),
  eq({
    id: "en|sva|16",
    difficulty: "difficult",
    skill: "subject-verb-agreement",
    stem: "Which is grammatically clean?",
    options: [
      "Every one of the windows needs repair.",
      "Every one of the windows need repair.",
      "Every one of the windows are needing repair.",
      "Every one of the windows have needed repair.",
    ],
    correctIndex: 0,
    explanation: "Every one is singular → needs. Windows is the trap noun.",
  }),

  // Tense
  eq({
    id: "en|tns|1",
    difficulty: "easy",
    skill: "tense-consistency",
    stem: "By the time we arrived, the lecture ____.",
    options: ["had ended", "has ended", "ends", "will end"],
    correctIndex: 0,
    explanation: "Past of past: the ending happened before we arrived → past perfect.",
  }),
  eq({
    id: "en|tns|2",
    difficulty: "easy",
    skill: "tense-consistency",
    stem: "She usually ____ the market on Saturdays.",
    options: ["visits", "visited", "has visit", "visiting"],
    correctIndex: 0,
    explanation: "Usually + Saturdays → present simple habit.",
  }),
  eq({
    id: "en|tns|3",
    difficulty: "hard",
    skill: "tense-consistency",
    stem: "If the river rises tonight, we ____ the lower road.",
    options: ["will close", "closed", "had closed", "closing"],
    correctIndex: 0,
    explanation: "First conditional: if + present, will + verb.",
  }),
  eq({
    id: "en|tns|4",
    difficulty: "hard",
    skill: "tense-consistency",
    stem: "He said he ____ the letter the previous day.",
    options: ["had posted", "has posted", "posts", "will post"],
    correctIndex: 0,
    explanation: "Reported speech + previous day → past perfect.",
  }),
  eq({
    id: "en|tns|5",
    difficulty: "difficult",
    skill: "tense-consistency",
    stem: "Choose the sentence with consistent tense.",
    options: [
      "She opened the door, looked down the path, and waited.",
      "She opened the door, looks down the path, and waited.",
      "She opens the door, looked down the path, and waited.",
      "She opened the door, looking down the path, and waits.",
    ],
    correctIndex: 0,
    explanation: "All three verbs stay in simple past. Mixed present/past is the trap.",
  }),
  eq({
    id: "en|tns|6",
    difficulty: "easy",
    skill: "tense-consistency",
    stem: "I ____ here since six o'clock.",
    options: ["have been waiting", "am waiting", "wait", "had wait"],
    correctIndex: 0,
    explanation: "Since + a point in time → present perfect continuous.",
  }),
  eq({
    id: "en|tns|7",
    difficulty: "hard",
    skill: "tense-consistency",
    stem: "While the others ____, Ngozi finished the diagram.",
    options: ["were talking", "are talking", "talk", "have talk"],
    correctIndex: 0,
    explanation: "Interrupted background action in the past → past continuous.",
  }),
  eq({
    id: "en|tns|8",
    difficulty: "difficult",
    skill: "tense-consistency",
    stem: "If I ____ the width first, I would not have misdrawn the rectangle.",
    options: ["had measured", "have measured", "measured", "will measure"],
    correctIndex: 0,
    explanation: "Past counterfactual (third conditional): if + past perfect, would have.",
  }),
  eq({
    id: "en|tns|9",
    difficulty: "hard",
    skill: "tense-consistency",
    stem: "This time tomorrow we ____ the last paper.",
    options: ["will be sitting", "sat", "have sat", "are sat"],
    correctIndex: 0,
    explanation: "This time tomorrow → future continuous.",
  }),
  eq({
    id: "en|tns|10",
    difficulty: "easy",
    skill: "tense-consistency",
    stem: "The train ____ before we reached the station.",
    options: ["had left", "has left", "leaves", "is leaving"],
    correctIndex: 0,
    explanation: "One past action before another past action → had left.",
  }),
  eq({
    id: "en|tns|11",
    difficulty: "difficult",
    skill: "tense-consistency",
    stem: "Which sentence is tense-consistent?",
    options: [
      "Whenever she reads a contract, she notes every except.",
      "Whenever she reads a contract, she noted every except.",
      "Whenever she read a contract, she notes every except.",
      "Whenever she was reading a contract, she notes every except.",
    ],
    correctIndex: 0,
    explanation: "Whenever + present habit stays in the present. Mixing noted/notes is the error.",
  }),
  eq({
    id: "en|tns|12",
    difficulty: "hard",
    skill: "tense-consistency",
    stem: "I wish I ____ the extra hour for the hard questions.",
    options: ["had saved", "save", "am saving", "have save"],
    correctIndex: 0,
    explanation: "Wish about the past → past perfect.",
  }),
  eq({
    id: "en|tns|13",
    difficulty: "easy",
    skill: "tense-consistency",
    stem: "Look — the children ____ across the field right now.",
    options: ["are running", "run", "ran", "have run"],
    correctIndex: 0,
    explanation: "Right now → present continuous.",
  }),
  eq({
    id: "en|tns|14",
    difficulty: "difficult",
    skill: "tense-consistency",
    stem: "No sooner ____ the bell than the corridor filled.",
    options: ["had it rung", "it rings", "it has rung", "it was ring"],
    correctIndex: 0,
    explanation: "No sooner had + past participle… than. Inversion is required.",
  }),
  eq({
    id: "en|tns|15",
    difficulty: "hard",
    skill: "tense-consistency",
    stem: "By next June she ____ three full mock exams.",
    options: ["will have taken", "has taken", "takes", "had took"],
    correctIndex: 0,
    explanation: "By + future date + completed action → future perfect.",
  }),
  eq({
    id: "en|tns|16",
    difficulty: "easy",
    skill: "tense-consistency",
    stem: "Water ____ at 100 degrees Celsius at standard pressure.",
    options: ["boils", "is boiling", "boiled", "has boil"],
    correctIndex: 0,
    explanation: "Scientific fact → present simple, not present continuous.",
  }),

  // Pronoun reference
  eq({
    id: "en|prn|1",
    difficulty: "easy",
    skill: "pronoun-reference",
    stem: "Choose the sentence with a clear pronoun.",
    options: [
      "After Amina spoke to Chika, Amina left.",
      "After Amina spoke to Chika, she left.",
      "After Amina spoke to Chika, they left her.",
      "After Amina spoke to Chika, it left.",
    ],
    correctIndex: 0,
    explanation: "She could be Amina or Chika. Repeating the name removes the ambiguity.",
  }),
  eq({
    id: "en|prn|2",
    difficulty: "easy",
    skill: "pronoun-reference",
    stem: "Everyone must bring ____ own pencil.",
    options: ["his or her", "theirself", "its", "he"],
    correctIndex: 0,
    explanation: "Everyone is singular in formal exam English → his or her. Theirself is not standard.",
  }),
  eq({
    id: "en|prn|3",
    difficulty: "hard",
    skill: "pronoun-reference",
    stem: "Which sentence avoids a faulty pronoun?",
    options: [
      "The teachers collected the scripts and locked the scripts in the office.",
      "The teachers collected the scripts and locked them in the office.",
      "The teachers collected the scripts and locked they in the office.",
      "The teachers collected the scripts and locked it in the office.",
    ],
    correctIndex: 0,
    explanation:
      "Them could mean teachers or scripts. Repeating scripts is inelegant but clear — and on a precision test, clarity wins. It disagrees in number.",
  }),
  eq({
    id: "en|prn|4",
    difficulty: "hard",
    skill: "pronoun-reference",
    stem: "Neither of the girls finished ____ assignment.",
    options: ["her", "their", "its", "they"],
    correctIndex: 0,
    explanation: "Neither is singular → her. Their is the informal trap.",
  }),
  eq({
    id: "en|prn|5",
    difficulty: "difficult",
    skill: "pronoun-reference",
    stem: "Which is the only grammatically clean sentence?",
    options: [
      "The school asked parents to sign the form before the trip.",
      "The school asked parents to sign their form before they left.",
      "The school asked parents to sign them before the trip.",
      "The school asked parents to sign it before they left.",
    ],
    correctIndex: 0,
    explanation:
      "Their/they/it/them can point at school, parents, form, or trip. Naming the form and the trip removes the tangle.",
  }),
  eq({
    id: "en|prn|6",
    difficulty: "easy",
    skill: "pronoun-reference",
    stem: "The dog chased the cat until ____ climbed the tree.",
    options: ["the cat", "it", "they", "she"],
    correctIndex: 0,
    explanation: "It could be dog or cat. Naming the cat is the only unambiguous choice.",
  }),
  eq({
    id: "en|prn|7",
    difficulty: "hard",
    skill: "pronoun-reference",
    stem: "One should not waste ____ time on the first trap.",
    options: ["one's", "their", "your", "its"],
    correctIndex: 0,
    explanation: "One pairs with one's in formal usage. Their/your shift person.",
  }),
  eq({
    id: "en|prn|8",
    difficulty: "difficult",
    skill: "pronoun-reference",
    stem: "Identify the sentence without a vague this/that.",
    options: [
      "The experiment failed because the sample was wet, a problem we can fix.",
      "The experiment failed. This is a problem.",
      "The experiment failed, and that was why.",
      "The experiment failed, which they knew.",
    ],
    correctIndex: 0,
    explanation: "This/that/which have no single noun to sit on. Naming “a problem we can fix” after a clause is still clearer than a floating this.",
  }),
  eq({
    id: "en|prn|9",
    difficulty: "hard",
    skill: "pronoun-reference",
    stem: "Each of the boys carried ____ bag to the hall.",
    options: ["his", "their", "they", "them"],
    correctIndex: 0,
    explanation: "Each → singular his. Their agrees with boys, the trap noun.",
  }),
  eq({
    id: "en|prn|10",
    difficulty: "easy",
    skill: "pronoun-reference",
    stem: "The committee made ____ decision after midnight.",
    options: ["its", "their", "it's", "there"],
    correctIndex: 0,
    explanation: "Committee as a unit → its. It's = it is; there is a place.",
  }),
  eq({
    id: "en|prn|11",
    difficulty: "difficult",
    skill: "pronoun-reference",
    stem: "Which sentence has a clear antecedent?",
    options: [
      "When the glass hit the tile, the glass cracked.",
      "When the glass hit the tile, it cracked.",
      "When the glass hit the tile, they cracked.",
      "When the glass hit the tile, this cracked.",
    ],
    correctIndex: 0,
    explanation: "It could be glass or tile. Repeating glass is the precise fix.",
  }),
  eq({
    id: "en|prn|12",
    difficulty: "hard",
    skill: "pronoun-reference",
    stem: "Let every candidate check that ____ script is signed.",
    options: ["his or her", "they", "them", "theirs'"],
    correctIndex: 0,
    explanation: "Every candidate is singular in exam English.",
  }),
  eq({
    id: "en|prn|13",
    difficulty: "easy",
    skill: "pronoun-reference",
    stem: "____ is raining, so the match is indoors.",
    options: ["It", "This", "They", "These"],
    correctIndex: 0,
    explanation: "Weather it is a dummy pronoun and is standard. This needs a noun nearby.",
  }),
  eq({
    id: "en|prn|14",
    difficulty: "difficult",
    skill: "pronoun-reference",
    stem: "Choose the cleanest version.",
    options: [
      "Jide told Tunde that Tunde had won.",
      "Jide told Tunde that he had won.",
      "Jide told Tunde that they had won.",
      "Jide told Tunde that it had won.",
    ],
    correctIndex: 0,
    explanation: "He is fatally ambiguous. Repeating Tunde is the only option that names the winner.",
  }),
  eq({
    id: "en|prn|15",
    difficulty: "hard",
    skill: "pronoun-reference",
    stem: "The jury has reached ____ verdict.",
    options: ["its", "their", "it's", "there"],
    correctIndex: 0,
    explanation: "Jury as one body → its. Their treats the jury as individuals, which this sentence does not.",
  }),
  eq({
    id: "en|prn|16",
    difficulty: "easy",
    skill: "pronoun-reference",
    stem: "Somebody left ____ umbrella by the door.",
    options: ["an", "theirselves", "they", "them"],
    correctIndex: 0,
    explanation:
      "The only clean choice among these is an umbrella — avoiding a disputed pronoun. Theirselves/they/them are ungrammatical here.",
  }),

  // Semicolons
  eq({
    id: "en|sc|1",
    difficulty: "easy",
    skill: "semicolons",
    stem: "Which sentence uses the semicolon correctly?",
    options: [
      "The hall was full; we stood at the back.",
      "The hall was full; and we stood at the back.",
      "The hall was full; at the back.",
      "The hall was full, we stood at the back.",
    ],
    correctIndex: 0,
    explanation: "Two independent clauses, no coordinating conjunction after the semicolon. The comma splice is the last option.",
  }),
  eq({
    id: "en|sc|2",
    difficulty: "easy",
    skill: "semicolons",
    stem: "Choose the correct punctuation.",
    options: [
      "Bring a pencil, a ruler, and an eraser.",
      "Bring a pencil; a ruler; and an eraser.",
      "Bring a pencil; a ruler, and an eraser.",
      "Bring a pencil a ruler and an eraser;",
    ],
    correctIndex: 0,
    explanation: "Simple lists take commas. Semicolons belong in lists only when items already contain commas.",
  }),
  eq({
    id: "en|sc|3",
    difficulty: "hard",
    skill: "semicolons",
    stem: "Which is correct?",
    options: [
      "She wanted to leave; however, the gate was locked.",
      "She wanted to leave; however the gate was locked.",
      "She wanted to leave, however; the gate was locked.",
      "She wanted to leave however; the gate was locked.",
    ],
    correctIndex: 0,
    explanation: "Independent clause; conjunctive adverb, independent clause. However needs a comma after it in this pattern.",
  }),
  eq({
    id: "en|sc|4",
    difficulty: "hard",
    skill: "semicolons",
    stem: "Select the properly punctuated sentence.",
    options: [
      "We visited Lagos, Nigeria; Accra, Ghana; and Dakar, Senegal.",
      "We visited Lagos, Nigeria, Accra, Ghana, and Dakar, Senegal.",
      "We visited Lagos; Nigeria; Accra; Ghana; and Dakar; Senegal.",
      "We visited Lagos, Nigeria; Accra, Ghana, and Dakar, Senegal.",
    ],
    correctIndex: 0,
    explanation: "List items that already contain commas are separated by semicolons. All-commas makes city/country boundaries unclear.",
  }),
  eq({
    id: "en|sc|5",
    difficulty: "difficult",
    skill: "semicolons",
    stem: "Which sentence is the only clean one?",
    options: [
      "The rule is simple: read the qualifier; then choose.",
      "The rule is simple; read the qualifier, then choose;",
      "The rule is simple; read the qualifier; then choose;",
      "The rule is simple, read the qualifier; then choose.",
    ],
    correctIndex: 0,
    explanation: "Colon introduces the explanation; the semicolon then joins two short related commands. Trailing semicolons and comma splices fail.",
  }),
  eq({
    id: "en|sc|6",
    difficulty: "easy",
    skill: "semicolons",
    stem: "A semicolon is most appropriate in which case?",
    options: [
      "Linking two closely related independent clauses",
      "Introducing a list after a verb",
      "Marking a possessive noun",
      "Joining a dependent clause to an independent one",
    ],
    correctIndex: 0,
    explanation: "A colon introduces a list; an apostrophe marks possession; a comma (or nothing extra) handles dependent clauses.",
  }),
  eq({
    id: "en|sc|7",
    difficulty: "hard",
    skill: "semicolons",
    stem: "Which sentence is correct?",
    options: [
      "I have the notes; I do not have the time.",
      "I have the notes; but I do not have the time.",
      "I have the notes; which I do not have the time.",
      "Although I have the notes; I do not have the time.",
    ],
    correctIndex: 0,
    explanation: "Do not put a semicolon before but or although. Those need a comma (or nothing, for although at the start).",
  }),
  eq({
    id: "en|sc|8",
    difficulty: "difficult",
    skill: "semicolons",
    stem: "Choose the sentence that is punctuated correctly.",
    options: [
      "He trained for months; the result, however, was still a fail.",
      "He trained for months, the result; however, was still a fail.",
      "He trained for months; the result however was still a fail.",
      "He trained for months the result, however; was still a fail.",
    ],
    correctIndex: 0,
    explanation: "Clause; noun, however, rest of clause. However as interrupter takes two commas; the semicolon sits between clauses.",
  }),
  eq({
    id: "en|sc|9",
    difficulty: "easy",
    skill: "semicolons",
    stem: "Find the error-free sentence.",
    options: [
      "Finish the easy items first; leave the long ones for later.",
      "Finish the easy items first; and leave the long ones for later.",
      "Finish the easy items first, leave the long ones for later.",
      "Finish the easy items first; leaving the long ones for later.",
    ],
    correctIndex: 0,
    explanation: "Two imperatives are independent clauses. And after a semicolon is extra; the comma splice is option 3; a fragment follows in option 4.",
  }),
  eq({
    id: "en|sc|10",
    difficulty: "hard",
    skill: "semicolons",
    stem: "Which uses the semicolon as a super-comma in a list?",
    options: [
      "The dates are 12 January, 2024; 3 March, 2024; and 8 July, 2024.",
      "The dates are 12 January; 2024, 3 March; 2024, and 8 July; 2024.",
      "The dates are: 12 January, 2024, 3 March, 2024 and 8 July, 2024.",
      "The dates are 12 January 2024 3 March 2024 and 8 July 2024;",
    ],
    correctIndex: 0,
    explanation: "Each date already has a comma, so semicolons separate the dates.",
  }),
  eq({
    id: "en|sc|11",
    difficulty: "difficult",
    skill: "semicolons",
    stem: "Which sentence is correct?",
    options: [
      "Call me when you arrive; I will meet you at the gate.",
      "Call me when you arrive; and I will meet you at the gate.",
      "When you arrive; I will meet you at the gate.",
      "Call me when you arrive I will meet you at the gate;",
    ],
    correctIndex: 0,
    explanation: "When you arrive is dependent — it cannot stand after a semicolon as a full clause on its own (option 3).",
  }),
  eq({
    id: "en|sc|12",
    difficulty: "easy",
    skill: "semicolons",
    stem: "A comma splice is",
    options: [
      "two independent clauses joined by only a comma",
      "a semicolon used in a simple list",
      "a missing apostrophe",
      "a colon after a complete sentence",
    ],
    correctIndex: 0,
    explanation: "The definition itself is the tested idea — and the thing a semicolon is meant to repair.",
  }),
  eq({
    id: "en|sc|13",
    difficulty: "hard",
    skill: "semicolons",
    stem: "Pick the correctly punctuated line.",
    options: [
      "The first test was timed; the second was not.",
      "The first test was timed, the second was not.",
      "The first test was timed; but the second was not.",
      "The first test was timed the second; was not.",
    ],
    correctIndex: 0,
    explanation: "Two balanced independent clauses. Option 2 is a comma splice; option 3 adds but after a semicolon.",
  }),
  eq({
    id: "en|sc|14",
    difficulty: "difficult",
    skill: "semicolons",
    stem: "Which is acceptable?",
    options: [
      "Some candidates sprint; others, wisely, skip.",
      "Some candidates sprint, others, wisely skip.",
      "Some candidates sprint; others wisely; skip.",
      "Some candidates sprint others; wisely, skip.",
    ],
    correctIndex: 0,
    explanation: "Others, wisely, skip is still an independent clause with a parenthetical wisely.",
  }),
  eq({
    id: "en|sc|15",
    difficulty: "easy",
    skill: "semicolons",
    stem: "You should not use a semicolon to",
    options: [
      "introduce a list after a verb such as include",
      "join two related independent clauses",
      "separate complex list items that already contain commas",
      "sit before a conjunctive adverb such as therefore",
    ],
    correctIndex: 0,
    explanation: "Introduce a list with a colon, not a semicolon, especially after include.",
  }),
  eq({
    id: "en|sc|16",
    difficulty: "hard",
    skill: "semicolons",
    stem: "Which sentence is correct?",
    options: [
      "The clock is the filter; it does not care that you almost had it.",
      "The clock is the filter, it does not care that you almost had it.",
      "The clock is the filter; and it does not care that you almost had it.",
      "The clock is the filter; not caring that you almost had it.",
    ],
    correctIndex: 0,
    explanation: "Two full sentences, related, no extra and. Option 4 leaves a fragment after the semicolon.",
  }),
];
