import type { Question, Skill, Tier } from "./types";

type Spec = {
  id: string;
  difficulty: Tier;
  skill: Skill;
  stem: string;
  options: [string, string, string, string];
  correctIndex: 0 | 1 | 2 | 3;
  explanation: string;
};

function g(s: Spec): Question {
  return { subject: "gk", ...s };
}

export const GK_BANK: Question[] = [
  g({
    id: "gk|gen|1",
    difficulty: "easy",
    skill: "genetics",
    stem: "In Mendel's pea experiments, a trait that is hidden in a hybrid (heterozygous) generation is called",
    options: ["recessive", "dominant", "mutant", "clonal"],
    correctIndex: 0,
    explanation: "The hidden form is recessive; the expressed form in the hybrid is dominant. Mutant is a neighbouring biology word, not Mendel's term here.",
  }),
  g({
    id: "gk|gen|2",
    difficulty: "easy",
    skill: "genetics",
    stem: "DNA is found mainly in which part of an animal cell?",
    options: ["nucleus", "cell wall", "vacuole", "ribosome"],
    correctIndex: 0,
    explanation: "Nuclear DNA sits in the nucleus. Animal cells have no cell wall — that option is a plant-context trap.",
  }),
  g({
    id: "gk|gen|3",
    difficulty: "hard",
    skill: "genetics",
    stem: "If brown eyes (B) are dominant to blue (b), two Bb parents have a child. The probability the child has blue eyes is",
    options: ["1/4", "1/2", "3/4", "1"],
    correctIndex: 0,
    explanation: "bb is 1 of 4 Punnett squares. 3/4 is the brown-eyed trap (the complement).",
  }),
  g({
    id: "gk|gen|4",
    difficulty: "hard",
    skill: "genetics",
    stem: "A gene is best described as",
    options: [
      "a stretch of DNA that codes for a product, usually a protein",
      "a whole chromosome",
      "any mutation in a cell",
      "the shape of a nucleus",
    ],
    correctIndex: 0,
    explanation: "Genes are DNA segments. A chromosome carries many genes — the scale trap.",
  }),
  g({
    id: "gk|gen|5",
    difficulty: "difficult",
    skill: "genetics",
    stem: "Why can two brown-eyed parents have a blue-eyed child?",
    options: [
      "Each parent can carry a hidden recessive allele",
      "Eye colour is not inherited",
      "Blue is always dominant",
      "The child must have a mutation in every case",
    ],
    correctIndex: 0,
    explanation: "Both parents can be heterozygous. “Blue is dominant” reverses the usual teaching example.",
  }),
  g({
    id: "gk|gen|6",
    difficulty: "easy",
    skill: "genetics",
    stem: "Which base pairs with adenine in DNA?",
    options: ["thymine", "uracil", "guanine", "ribose"],
    correctIndex: 0,
    explanation: "A–T in DNA. Uracil pairs with adenine in RNA — the neighbouring-molecule trap.",
  }),
  g({
    id: "gk|gen|7",
    difficulty: "hard",
    skill: "genetics",
    stem: "Photosynthesis in green plants mainly takes place in the",
    options: ["chloroplasts", "mitochondria", "nucleus", "stomata only"],
    correctIndex: 0,
    explanation: "Chloroplasts house the chlorophyll machinery. Mitochondria are the respiration trap. Stomata are pores, not the site of the reactions.",
  }),
  g({
    id: "gk|gen|8",
    difficulty: "difficult",
    skill: "genetics",
    stem: "Identical twins have the same genotype at birth but may differ later in height. This is evidence that",
    options: [
      "environment as well as genes can shape a trait",
      "genes do not affect height",
      "twins do not share DNA",
      "height is purely random",
    ],
    correctIndex: 0,
    explanation: "Same genes, different outcomes → environment (and chance) matter. “Genes do not affect height” overcorrects.",
  }),
  g({
    id: "gk|gov|1",
    difficulty: "easy",
    skill: "government",
    stem: "Nigeria's National Assembly is made up of",
    options: [
      "the Senate and the House of Representatives",
      "the Senate and the Supreme Court",
      "state governors and the Senate",
      "local government chairmen only",
    ],
    correctIndex: 0,
    explanation: "Bicameral legislature: Senate + House. The Supreme Court is the judiciary — a neighbouring-branch trap.",
  }),
  g({
    id: "gk|gov|2",
    difficulty: "easy",
    skill: "government",
    stem: "The capital city of Nigeria is",
    options: ["Abuja", "Lagos", "Kano", "Port Harcourt"],
    correctIndex: 0,
    explanation: "Abuja is the capital. Lagos is the former capital and the population trap.",
  }),
  g({
    id: "gk|gov|3",
    difficulty: "hard",
    skill: "government",
    stem: "Separation of powers means that",
    options: [
      "law-making, enforcing, and judging are given to different bodies",
      "each state may print its own money",
      "the president also sits as chief judge",
      "elections are held every year",
    ],
    correctIndex: 0,
    explanation: "Legislature, executive, judiciary. The president-as-judge option is the opposite of the idea.",
  }),
  g({
    id: "gk|gov|4",
    difficulty: "hard",
    skill: "government",
    stem: "A constitution is best described as",
    options: [
      "the supreme set of rules that organises and limits government",
      "the speech a president gives each year",
      "a list of current office holders",
      "the ruling party's campaign manifesto",
    ],
    correctIndex: 0,
    explanation: "A constitution binds even the people who wrote yesterday's manifesto. Manifesto is the neighbouring-document trap.",
  }),
  g({
    id: "gk|gov|5",
    difficulty: "difficult",
    skill: "government",
    stem: "Federalism, in the Nigerian sense, mainly means that",
    options: [
      "power is shared between a central government and states",
      "all power sits in one city",
      "traditional rulers make national law",
      "the army appoints civilian ministers",
    ],
    correctIndex: 0,
    explanation: "Shared centre/states. “All power in one city” is unitarism — the antonym trap.",
  }),
  g({
    id: "gk|gov|6",
    difficulty: "easy",
    skill: "government",
    stem: "The three arms of government are",
    options: [
      "executive, legislature, judiciary",
      "police, army, customs",
      "federal, state, traditional",
      "president, governor, chairman",
    ],
    correctIndex: 0,
    explanation: "Functions, not levels or security agencies. Federal/state/local is a different classification.",
  }),
  g({
    id: "gk|gov|7",
    difficulty: "hard",
    skill: "government",
    stem: "A bill becomes an Act when it has been",
    options: [
      "passed by the legislature and assented to as the law requires",
      "read on television",
      "signed by a party chairman",
      "published in a newspaper editorial",
    ],
    correctIndex: 0,
    explanation: "Passage + assent (or the override procedure). Media publication is not enactment.",
  }),
  g({
    id: "gk|gov|8",
    difficulty: "difficult",
    skill: "government",
    stem: "An independent judiciary matters most because it",
    options: [
      "can check the other arms against the constitution",
      "writes the annual budget",
      "commands the armed forces",
      "registers political parties",
    ],
    correctIndex: 0,
    explanation: "Checking power is the job. Budgets, armies, and party registers belong to other bodies.",
  }),
  g({
    id: "gk|eco|1",
    difficulty: "easy",
    skill: "economics",
    stem: "If the price of a good rises and nothing else changes, quantity demanded usually",
    options: ["falls", "rises", "stays exactly the same by law", "becomes infinite"],
    correctIndex: 0,
    explanation: "Law of demand. “Rises” is the supply-side mix-up.",
  }),
  g({
    id: "gk|eco|2",
    difficulty: "easy",
    skill: "economics",
    stem: "A market is, at root,",
    options: [
      "any arrangement in which buyers and sellers exchange",
      "only a physical shop with a roof",
      "a government warehouse",
      "a bank's list of debtors",
    ],
    correctIndex: 0,
    explanation: "Markets can be stalls, apps, or contracts. “Physical shop” is the everyday-meaning trap.",
  }),
  g({
    id: "gk|eco|3",
    difficulty: "hard",
    skill: "economics",
    stem: "Opportunity cost is",
    options: [
      "the next-best alternative you give up",
      "the money price printed on a tag",
      "a tax paid to local government",
      "the cost of transporting goods",
    ],
    correctIndex: 0,
    explanation: "What you forgo, not just the naira on the tag. Tag price is the neighbouring idea.",
  }),
  g({
    id: "gk|eco|4",
    difficulty: "hard",
    skill: "economics",
    stem: "Inflation means",
    options: [
      "a sustained rise in the general price level",
      "a one-day rise in one shop's prices",
      "an increase in the number of shops",
      "a fall in all wages at once",
    ],
    correctIndex: 0,
    explanation: "General and sustained. One shop, one day is not inflation.",
  }),
  g({
    id: "gk|eco|5",
    difficulty: "difficult",
    skill: "economics",
    stem: "A country that exports crude oil and imports petrol is mainly selling a ____ and buying a ____.",
    options: [
      "raw material; processed good",
      "processed good; raw material",
      "service; raw material",
      "currency; raw material",
    ],
    correctIndex: 0,
    explanation: "Crude is primary; petrol is refined. Reversing the pair is the trap.",
  }),
  g({
    id: "gk|eco|6",
    difficulty: "easy",
    skill: "economics",
    stem: "Which of these is a factor of production?",
    options: ["labour", "a finished loaf of bread", "a customer's taste", "a tax receipt"],
    correctIndex: 0,
    explanation: "Land, labour, capital, entrepreneurship. A loaf is output, not a factor.",
  }),
  g({
    id: "gk|eco|7",
    difficulty: "hard",
    skill: "economics",
    stem: "A surplus in a competitive market tends to",
    options: [
      "push prices down toward equilibrium",
      "push prices up immediately",
      "ban all further production",
      "have no effect on price",
    ],
    correctIndex: 0,
    explanation: "Surplus → sellers cut prices. Shortage would push prices up — the complement trap.",
  }),
  g({
    id: "gk|eco|8",
    difficulty: "difficult",
    skill: "economics",
    stem: "“The minimum wage rose 20%; therefore every worker is 20% better off.” The main flaw is that the speaker",
    options: [
      "ignores prices, hours, and who is covered by the wage",
      "uses the wrong currency",
      "assumes wages never change",
      "forgets that 20% is a large number",
    ],
    correctIndex: 0,
    explanation: "A silent-killer reasoning item: the jump from a headline rate to “every worker” skips inflation, coverage, and hours.",
  }),
  g({
    id: "gk|sci|1",
    difficulty: "easy",
    skill: "science",
    stem: "The process by which green plants make food using sunlight is",
    options: ["photosynthesis", "respiration", "fermentation", "transpiration"],
    correctIndex: 0,
    explanation: "Photosynthesis. Respiration is the neighbouring energy process; transpiration is water loss.",
  }),
  g({
    id: "gk|sci|2",
    difficulty: "easy",
    skill: "science",
    stem: "Water boils at 100°C at standard atmospheric pressure. This is a",
    options: ["physical change of state", "chemical reaction that makes a new substance", "nuclear change", "magnetic change"],
    correctIndex: 0,
    explanation: "Boiling is liquid → gas. No new substance, so not chemical.",
  }),
  g({
    id: "gk|sci|3",
    difficulty: "hard",
    skill: "science",
    stem: "Which planet is closest to the Sun?",
    options: ["Mercury", "Venus", "Earth", "Mars"],
    correctIndex: 0,
    explanation: "Mercury, then Venus. Venus is the “hottest planet” neighbour, not the closest.",
  }),
  g({
    id: "gk|sci|4",
    difficulty: "hard",
    skill: "science",
    stem: "An object at rest stays at rest unless a net force acts on it. This is",
    options: ["Newton's first law", "Newton's second law", "Ohm's law", "the law of conservation of mass"],
    correctIndex: 0,
    explanation: "Inertia / first law. Second law is F = ma — the neighbouring Newton trap.",
  }),
  g({
    id: "gk|sci|5",
    difficulty: "difficult",
    skill: "science",
    stem: "Metals generally conduct electricity well because they have",
    options: [
      "delocalised electrons that can move",
      "more protons than non-metals",
      "no atoms",
      "a positive charge on the whole lump",
    ],
    correctIndex: 0,
    explanation: "Mobile electrons. “More protons” is a half-remembered periodic-table idea.",
  }),
  g({
    id: "gk|sci|6",
    difficulty: "easy",
    skill: "science",
    stem: "The smallest unit of an element that still has that element's properties is the",
    options: ["atom", "mixture", "solution", "molecule of a compound"],
    correctIndex: 0,
    explanation: "Atom. A compound's molecule is made of more than one element.",
  }),
  g({
    id: "gk|sci|7",
    difficulty: "hard",
    skill: "science",
    stem: "Vaccines work primarily by",
    options: [
      "training the immune system to recognise a pathogen",
      "killing every bacterium in the body at once",
      "replacing DNA in every cell",
      "raising body temperature permanently",
    ],
    correctIndex: 0,
    explanation: "Recognition and memory, not a one-shot sterilisation of the body.",
  }),
  g({
    id: "gk|sci|8",
    difficulty: "difficult",
    skill: "science",
    stem: "A closed bottle of cold water left in a warm room collects droplets on the outside. The water on the outside came from",
    options: [
      "water vapour in the air that condensed",
      "the cold water leaking through the plastic",
      "the bottle melting",
      "hydrogen and oxygen combining on the surface",
    ],
    correctIndex: 0,
    explanation: "Condensation of humid air. Leakage is the careless physical trap.",
  }),
  g({
    id: "gk|geo|1",
    difficulty: "easy",
    skill: "geography",
    stem: "The River Niger empties into the",
    options: ["Atlantic Ocean (Gulf of Guinea)", "Mediterranean Sea", "Indian Ocean", "Red Sea"],
    correctIndex: 0,
    explanation: "Niger Delta on the Gulf of Guinea. Mediterranean is a North-Africa neighbour.",
  }),
  g({
    id: "gk|geo|2",
    difficulty: "easy",
    skill: "geography",
    stem: "The equator is",
    options: [
      "an imaginary line around the Earth, halfway between the poles",
      "the line that divides Africa from Europe",
      "the path of the Moon",
      "the deepest ocean trench",
    ],
    correctIndex: 0,
    explanation: "0° latitude. Europe/Africa is the Strait of Gibraltar — a neighbouring map fact.",
  }),
  g({
    id: "gk|geo|3",
    difficulty: "hard",
    skill: "geography",
    stem: "Which West African country is landlocked?",
    options: ["Burkina Faso", "Ghana", "Senegal", "Côte d'Ivoire"],
    correctIndex: 0,
    explanation: "Burkina Faso has no coast. The others are coastal — the regional trap is to pick a familiar coastal name.",
  }),
  g({
    id: "gk|geo|4",
    difficulty: "hard",
    skill: "geography",
    stem: "A scale of 1:50,000 on a map means that 1 cm on the map represents",
    options: ["0.5 km on the ground", "50 km on the ground", "5 m on the ground", "50,000 km on the ground"],
    correctIndex: 0,
    explanation: "1 cm → 50,000 cm = 500 m = 0.5 km. 50 km forgets to convert centimetres.",
  }),
  g({
    id: "gk|geo|5",
    difficulty: "difficult",
    skill: "geography",
    stem: "Harmattan is best described as",
    options: [
      "a dry, dusty wind from the Sahara that affects West Africa in the dry season",
      "a tropical cyclone in the Atlantic",
      "the rainy-season monsoon of South Asia",
      "a warm ocean current off Namibia",
    ],
    correctIndex: 0,
    explanation: "Regional climate, not a cyclone or the Asian monsoon — neighbouring wind/rain words.",
  }),
  g({
    id: "gk|geo|6",
    difficulty: "easy",
    skill: "geography",
    stem: "The largest ocean on Earth is the",
    options: ["Pacific", "Atlantic", "Indian", "Arctic"],
    correctIndex: 0,
    explanation: "Pacific. Atlantic is the ocean most West African candidates meet first — the familiarity trap.",
  }),
  g({
    id: "gk|geo|7",
    difficulty: "hard",
    skill: "geography",
    stem: "Lake Chad is unusual among Africa's large lakes because it",
    options: [
      "has shrunk dramatically and is shared by several countries",
      "is the deepest lake on Earth",
      "has no fish",
      "lies entirely inside South Africa",
    ],
    correctIndex: 0,
    explanation: "Shared and much reduced. Deepest is Lake Tanganyika/Baikal territory — a different famous-lake fact.",
  }),
  g({
    id: "gk|geo|8",
    difficulty: "difficult",
    skill: "geography",
    stem: "Why are temperatures generally lower at the top of a mountain than at its base, even near the equator?",
    options: [
      "Air pressure and density fall with height, so the air holds and shares less heat",
      "The mountain is always farther from the Sun than the valley",
      "There is no sunlight on peaks",
      "Equatorial mountains are made of ice",
    ],
    correctIndex: 0,
    explanation: "Lapse rate / thinner air. “Farther from the Sun” is the naive-distance trap (the height difference is tiny astronomically).",
  }),
  g({
    id: "gk|his|1",
    difficulty: "easy",
    skill: "history",
    stem: "Nigeria became an independent country in",
    options: ["1960", "1963", "1999", "1914"],
    correctIndex: 0,
    explanation: "1 October 1960. 1914 is amalgamation; 1963 republic; 1999 return to civilian rule — neighbouring civic dates.",
  }),
  g({
    id: "gk|his|2",
    difficulty: "easy",
    skill: "history",
    stem: "The amalgamation of the Northern and Southern Protectorates of Nigeria took place in",
    options: ["1914", "1960", "1885", "1991"],
    correctIndex: 0,
    explanation: "1914. 1885 is Berlin Conference-ish; 1960 independence — date cluster trap.",
  }),
  g({
    id: "gk|his|3",
    difficulty: "hard",
    skill: "history",
    stem: "The Berlin Conference (1884–85) is most closely associated with",
    options: [
      "European powers setting rules for colonising Africa",
      "the founding of the United Nations",
      "Nigerian independence talks",
      "the end of the Second World War",
    ],
    correctIndex: 0,
    explanation: "Scramble for Africa. UN founding is 1945 — a different conference-in-Europe trap.",
  }),
  g({
    id: "gk|his|4",
    difficulty: "hard",
    skill: "history",
    stem: "World War II in Europe ended in",
    options: ["1945", "1918", "1939", "1960"],
    correctIndex: 0,
    explanation: "1945. 1918 is WWI; 1939 is the start of WWII — the neighbouring-year trap.",
  }),
  g({
    id: "gk|his|5",
    difficulty: "difficult",
    skill: "history",
    stem: "Trans-Saharan trade before colonial rule mainly exchanged",
    options: [
      "gold, salt, and other goods across desert routes",
      "crude oil for petrol",
      "computers for cocoa",
      "railway engines for cotton",
    ],
    correctIndex: 0,
    explanation: "Gold and salt are the classic pair. Oil/petrol is a modern Nigerian economy trap.",
  }),
  g({
    id: "gk|his|6",
    difficulty: "easy",
    skill: "history",
    stem: "The first man to walk on the Moon did so in",
    options: ["1969", "1957", "1979", "1945"],
    correctIndex: 0,
    explanation: "Apollo 11, 1969. 1957 is Sputnik — the space-race neighbour.",
  }),
  g({
    id: "gk|his|7",
    difficulty: "hard",
    skill: "history",
    stem: "ECOWAS was established primarily to",
    options: [
      "promote economic cooperation among West African states",
      "replace the United Nations in Africa",
      "govern Nigeria's local councils",
      "run the World Bank",
    ],
    correctIndex: 0,
    explanation: "Regional economic community. UN-replacement is scale inflation.",
  }),
  g({
    id: "gk|his|8",
    difficulty: "difficult",
    skill: "history",
    stem: "A primary source for a historian studying a 19th-century treaty is",
    options: [
      "the treaty text itself, written at the time",
      "a textbook chapter written last year",
      "a film set in the period",
      "a multiple-choice question about the treaty",
    ],
    correctIndex: 0,
    explanation: "Primary = produced at the time. A textbook is secondary — the neighbouring-term trap.",
  }),
  g({
    id: "gk|ins|1",
    difficulty: "easy",
    skill: "institutions",
    stem: "The United Nations was founded in",
    options: ["1945", "1919", "1960", "1991"],
    correctIndex: 0,
    explanation: "1945, after WWII. 1919 is the League of Nations — the predecessor trap.",
  }),
  g({
    id: "gk|ins|2",
    difficulty: "easy",
    skill: "institutions",
    stem: "The headquarters of the United Nations is in",
    options: ["New York", "Geneva only", "London", "Abuja"],
    correctIndex: 0,
    explanation: "UN HQ is New York. Geneva hosts many UN agencies — the partial-truth trap.",
  }),
  g({
    id: "gk|ins|3",
    difficulty: "hard",
    skill: "institutions",
    stem: "The UN Security Council's most distinctive power is that it can",
    options: [
      "authorise binding measures, including sanctions or force, for peace and security",
      "set interest rates for all countries",
      "appoint every national president",
      "rewrite a country's constitution without consent",
    ],
    correctIndex: 0,
    explanation: "Peace and security, including Chapter VII. Central-bank and constitution powers belong elsewhere.",
  }),
  g({
    id: "gk|ins|4",
    difficulty: "hard",
    skill: "institutions",
    stem: "The World Health Organization is a specialised agency of",
    options: ["the United Nations", "ECOWAS", "the African Union only", "FIFA"],
    correctIndex: 0,
    explanation: "WHO sits in the UN family. AU/ECOWAS are regional — neighbouring-institution traps.",
  }),
  g({
    id: "gk|ins|5",
    difficulty: "difficult",
    skill: "institutions",
    stem: "A veto in the UN Security Council means that",
    options: [
      "one permanent member can block a resolution even if others support it",
      "every country in the world must agree",
      "the Secretary-General can cancel a vote",
      "only African states may vote",
    ],
    correctIndex: 0,
    explanation: "P5 veto. “Every country must agree” confuses the Council with general consensus.",
  }),
  g({
    id: "gk|ins|6",
    difficulty: "easy",
    skill: "institutions",
    stem: "The African Union replaced which earlier body?",
    options: [
      "the Organisation of African Unity (OAU)",
      "ECOWAS",
      "the League of Nations",
      "the Commonwealth",
    ],
    correctIndex: 0,
    explanation: "OAU → AU (2002). ECOWAS is West Africa only.",
  }),
  g({
    id: "gk|ins|7",
    difficulty: "hard",
    skill: "institutions",
    stem: "The International Court of Justice sits in",
    options: ["The Hague", "New York", "Addis Ababa", "Paris"],
    correctIndex: 0,
    explanation: "ICJ in The Hague. New York is UN HQ — institution-city mix-up.",
  }),
  g({
    id: "gk|ins|8",
    difficulty: "difficult",
    skill: "institutions",
    stem: "UNESCO is most closely concerned with",
    options: [
      "education, science and culture",
      "military peacekeeping only",
      "setting oil prices",
      "running national elections",
    ],
    correctIndex: 0,
    explanation: "The name is the clue; peacekeeping is a different UN organ's tool.",
  }),
  g({
    id: "gk|rea|1",
    difficulty: "hard",
    skill: "reasoning",
    stem: "“Every student who passed scored above 80. Amaka scored 85. Therefore Amaka passed.” The hidden extra assumption is that",
    options: [
      "scoring above 80 is enough to pass, not merely something passers happen to have done",
      "Amaka sat the same paper as the others",
      "85 is a prime number",
      "no one scored 85",
    ],
    correctIndex: 0,
    explanation: "The given line is “if passed → >80”, which does not by itself give “>80 → passed.” That converse is the smuggled step.",
  }),
  g({
    id: "gk|rea|2",
    difficulty: "difficult",
    skill: "reasoning",
    stem: "A poster says: “9 out of 10 dentists recommend this paste.” Which question most undermines the claim?",
    options: [
      "How were the 10 dentists chosen, and who paid for the survey?",
      "Is ten a round number?",
      "Do dentists use toothpaste?",
      "Is the poster printed in colour?",
    ],
    correctIndex: 0,
    explanation: "Sampling and sponsorship go to whether the statistic means anything. Colour of the poster does not.",
  }),
  g({
    id: "gk|rea|3",
    difficulty: "hard",
    skill: "reasoning",
    stem: "“The library is empty; therefore students do not read.” The most serious flaw is",
    options: [
      "students may read elsewhere, at other hours, or on screens",
      "libraries are always empty",
      "reading cannot be measured",
      "empty rooms have no temperature",
    ],
    correctIndex: 0,
    explanation: "A single observation is made to carry a general conclusion. Alternative places and times are ignored.",
  }),
  g({
    id: "gk|rea|4",
    difficulty: "easy",
    skill: "reasoning",
    stem: "If all mammals have lungs, and a whale is a mammal, then",
    options: [
      "a whale has lungs",
      "a whale cannot live in water",
      "all animals with lungs are whales",
      "only whales are mammals",
    ],
    correctIndex: 0,
    explanation: "Valid deduction. “All animals with lungs are whales” reverses the universal — the classic trap.",
  }),
  g({
    id: "gk|rea|5",
    difficulty: "difficult",
    skill: "reasoning",
    stem: "A town's hospital births: 20 last year, 24 this year. A headline reads “Births jump 20% — baby boom.” The fairest criticism is that",
    options: [
      "a 20% rise from a small base may not be a boom",
      "24 is not divisible by 20",
      "hospitals never record births",
      "percentages cannot describe births",
    ],
    correctIndex: 0,
    explanation: "Same texture as the passage on denominators: 4 extra births is a large percentage and a small count.",
  }),
  g({
    id: "gk|rea|6",
    difficulty: "hard",
    skill: "reasoning",
    stem: "“No honest person would skip a question. You skipped one; you are dishonest.” This argument treats",
    options: [
      "skipping as if it could have only a moral cause",
      "honesty as undefined",
      "questions as illegal",
      "time as infinite",
    ],
    correctIndex: 0,
    explanation: "False dilemma / over-moralising: strategy, time, or confusion also explain a skip.",
  }),
  g({
    id: "gk|sci|9",
    difficulty: "easy",
    skill: "science",
    stem: "The gas most abundant in Earth's atmosphere is",
    options: ["nitrogen", "oxygen", "carbon dioxide", "hydrogen"],
    correctIndex: 0,
    explanation: "About 78% nitrogen. Oxygen (~21%) is the familiarity trap.",
  }),
  g({
    id: "gk|sci|10",
    difficulty: "hard",
    skill: "science",
    stem: "A lever is a simple machine. Its main job is to",
    options: [
      "change the force or distance needed to move a load",
      "create energy from nothing",
      "store electricity",
      "measure temperature",
    ],
    correctIndex: 0,
    explanation: "Machines trade force and distance; they do not create energy.",
  }),
  g({
    id: "gk|geo|9",
    difficulty: "easy",
    skill: "geography",
    stem: "The Sahara is",
    options: [
      "a vast desert in North Africa",
      "a rainforest in the Congo Basin",
      "a mountain range in East Africa",
      "a river in West Africa",
    ],
    correctIndex: 0,
    explanation: "Desert. Congo rainforest and East African highlands are neighbouring African biomes.",
  }),
  g({
    id: "gk|geo|10",
    difficulty: "hard",
    skill: "geography",
    stem: "Lines of longitude",
    options: [
      "run from pole to pole and measure east–west position",
      "run parallel to the equator and measure north–south position",
      "mark only national borders",
      "are visible from space as painted lines",
    ],
    correctIndex: 0,
    explanation: "Longitude = meridians, east–west position. The parallel/equator description is latitude — the swap trap.",
  }),
  g({
    id: "gk|gov|9",
    difficulty: "easy",
    skill: "government",
    stem: "A democracy, in the basic textbook sense, is a system in which",
    options: [
      "citizens choose leaders in reasonably free elections",
      "the army appoints the cabinet",
      "one family inherits all offices",
      "there are no laws",
    ],
    correctIndex: 0,
    explanation: "Competitive choice of leaders. Heredity is monarchy; army appointment is a different regime type.",
  }),
  g({
    id: "gk|gov|10",
    difficulty: "hard",
    skill: "government",
    stem: "Human rights are best thought of as",
    options: [
      "claims every person has, which government should not violate at will",
      "privileges a president may grant to supporters",
      "rules that apply only to adults in cities",
      "the same thing as a party manifesto",
    ],
    correctIndex: 0,
    explanation: "Rights are not gifts of the current office-holder. Manifesto is the neighbouring-document trap again.",
  }),
  g({
    id: "gk|eco|9",
    difficulty: "easy",
    skill: "economics",
    stem: "Barter is",
    options: [
      "exchange of goods for goods without money",
      "a tax on imports",
      "saving in a bank",
      "printing extra currency",
    ],
    correctIndex: 0,
    explanation: "Direct swap. Import tax is a tariff — another economics keyword.",
  }),
  g({
    id: "gk|eco|10",
    difficulty: "hard",
    skill: "economics",
    stem: "Division of labour means",
    options: [
      "splitting production into specialised tasks",
      "sacking half the workers",
      "paying everyone the same wage",
      "banning overtime",
    ],
    correctIndex: 0,
    explanation: "Specialisation. Sacking is a careless reading of “division.”",
  }),
  g({
    id: "gk|his|9",
    difficulty: "easy",
    skill: "history",
    stem: "The first World War ended in",
    options: ["1918", "1945", "1939", "1960"],
    correctIndex: 0,
    explanation: "Armistice 1918. 1945 is WWII — the usual mix-up.",
  }),
  g({
    id: "gk|his|10",
    difficulty: "hard",
    skill: "history",
    stem: "The Suez Canal connects",
    options: [
      "the Mediterranean Sea and the Red Sea",
      "the Atlantic and the Pacific at Panama",
      "Lake Victoria and the Nile only inside Uganda",
      "the Niger and the Benue",
    ],
    correctIndex: 0,
    explanation: "Mediterranean–Red Sea. Panama is the other famous canal — the swap trap.",
  }),
  g({
    id: "gk|gen|9",
    difficulty: "easy",
    skill: "science",
    stem: "The human heart's main job is to",
    options: ["pump blood around the body", "digest protein", "store urine", "make red bone from food"],
    correctIndex: 0,
    explanation: "Pump. Digestion and urine are neighbouring organ functions.",
  }),
  g({
    id: "gk|gen|10",
    difficulty: "hard",
    skill: "science",
    stem: "Antibiotics are used against",
    options: [
      "bacterial infections",
      "all viruses without exception",
      "broken bones",
      "vitamin deficiency",
    ],
    correctIndex: 0,
    explanation: "Bacteria, not viruses as a class. The “all viruses” option is the popular overreach.",
  }),
  g({
    id: "gk|ins|9",
    difficulty: "easy",
    skill: "institutions",
    stem: "FIFA is an organisation that governs",
    options: ["association football (soccer)", "the World Health Organization", "oil exports", "the International Court"],
    correctIndex: 0,
    explanation: "Football. WHO is health — acronym soup.",
  }),
  g({
    id: "gk|ins|10",
    difficulty: "hard",
    skill: "institutions",
    stem: "The Commonwealth is a grouping of",
    options: [
      "many countries with historical links to Britain, now voluntary members",
      "only African military governments",
      "the states of the USA",
      "oil-producing countries alone",
    ],
    correctIndex: 0,
    explanation: "Voluntary association with shared history, not OPEC and not the US federal states.",
  }),
  g({
    id: "gk|rea|7",
    difficulty: "easy",
    skill: "reasoning",
    stem: "A true statement: “All squares are rectangles.” Which must also be true?",
    options: [
      "Some rectangles are squares",
      "All rectangles are squares",
      "No rectangle is a square",
      "Squares are not quadrilaterals",
    ],
    correctIndex: 0,
    explanation: "The universal does not reverse. “All rectangles are squares” is the illicit conversion.",
  }),
  g({
    id: "gk|rea|8",
    difficulty: "difficult",
    skill: "reasoning",
    stem: "Study: towns with more firefighters have more fire damage. A politician concludes firefighters cause damage. The better explanation is that",
    options: [
      "a third factor (more fires) drives both firefighter numbers and damage",
      "firefighters never put out fires",
      "damage cannot be measured",
      "towns with firefighters have no water",
    ],
    correctIndex: 0,
    explanation: "Confounding / reverse causation. Firefighter numbers respond to fire risk.",
  }),
  g({
    id: "gk|geo|11",
    difficulty: "difficult",
    skill: "geography",
    stem: "West Africa's rainy season is driven mainly by",
    options: [
      "the seasonal shift of the Inter-Tropical Convergence Zone",
      "the melting of Antarctic ice each March",
      "monthly meetings of ECOWAS",
      "the phases of the Moon alone",
    ],
    correctIndex: 0,
    explanation: "ITCZ. Moon phases affecting rain is folklore-as-trap; ECOWAS is an institution, not a climate engine.",
  }),
  g({
    id: "gk|gov|11",
    difficulty: "difficult",
    skill: "government",
    stem: "A rule of law, as a principle, requires that",
    options: [
      "rulers as well as citizens are bound by known laws",
      "the longest-serving official may ignore the courts",
      "secret decrees replace published statutes",
      "only written customs of one ethnic group count",
    ],
    correctIndex: 0,
    explanation: "Nobody is above the law. Secret decrees are the opposite texture.",
  }),
  g({
    id: "gk|eco|11",
    difficulty: "difficult",
    skill: "economics",
    stem: "If a subsidy lowers the price buyers pay, and supply can expand, we should expect",
    options: [
      "a higher quantity bought and sold, other things equal",
      "the good to vanish from markets",
      "all imports to stop",
      "money to lose all value",
    ],
    correctIndex: 0,
    explanation: "Subsidy shifts effective supply; quantity typically rises. Vanishing is a price-ceiling shortage story, a neighbouring intervention.",
  }),
  g({
    id: "gk|sci|11",
    difficulty: "difficult",
    skill: "science",
    stem: "Why does a metal spoon in a hot pot heat up faster than a wooden spoon?",
    options: [
      "Metal is a better conductor of heat",
      "Metal is always hotter than wood at room temperature",
      "Wood cannot get warm",
      "The pot only touches metal spoons",
    ],
    correctIndex: 0,
    explanation: "Conduction. “Metal is always hotter” confuses conductivity with temperature.",
  }),
  g({
    id: "gk|his|11",
    difficulty: "difficult",
    skill: "history",
    stem: "Independence in 1960 did not, by itself, decide Nigeria's later system of government because",
    options: [
      "constitutions, coups, and reforms after 1960 continued to change the rules",
      "independence has no legal meaning",
      "Nigeria had no population in 1960",
      "all African states must use the same constitution",
    ],
    correctIndex: 0,
    explanation: "A date of independence is not a freeze-frame of institutions. The later record is the point.",
  }),
  g({
    id: "gk|ins|11",
    difficulty: "easy",
    skill: "institutions",
    stem: "Red Cross / Red Crescent societies are best known for",
    options: [
      "humanitarian help in conflict and disaster",
      "setting global interest rates",
      "organising the Olympics",
      "printing national currencies",
    ],
    correctIndex: 0,
    explanation: "Humanitarian mandate. Olympics is another well-known international brand — the swap.",
  }),
  g({
    id: "gk|gen|11",
    difficulty: "hard",
    skill: "genetics",
    stem: "Chromosomes are",
    options: [
      "structures of DNA and protein that carry genes",
      "sugars used in respiration",
      "holes in the nuclear membrane",
      "a type of white blood cell",
    ],
    correctIndex: 0,
    explanation: "DNA+protein packages. White blood cell is a different biology noun.",
  }),
  g({
    id: "gk|geo|12",
    difficulty: "easy",
    skill: "geography",
    stem: "Which country shares a land border with Nigeria?",
    options: ["Cameroon", "Ghana", "Kenya", "Egypt"],
    correctIndex: 0,
    explanation: "Cameroon (also Benin, Niger, Chad). Ghana is West African but not a neighbour — regional familiarity trap.",
  }),
  g({
    id: "gk|sci|12",
    difficulty: "easy",
    skill: "science",
    stem: "The Moon shines mainly because it",
    options: [
      "reflects sunlight",
      "burns like a star",
      "is covered in fireflies",
      "produces its own nuclear light at all times on the surface",
    ],
    correctIndex: 0,
    explanation: "Reflected sunlight. Burning like a star is the Sun-mix-up.",
  }),
];
